name: gotoyes

on:
  schedule:
    - cron: "55 */1 * * *"
  push:
    branches:
      - master:
      
jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "adu0928@163.com"
          git config --local user.name "adu0928"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "When you feel like hope is gone， look inside you and search your soul。 you will find a hero lies in you。 dreams are hard to follow， but don‘t let anyone steal your dream。
To be， or not to be - that is the question"
          git push
